"""Stage 5 ML models

Revision ID: 234108b9fd4e
Revises: 543ec1728025
Create Date: 2026-09-01 00:28:09.742165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234108b9fd4e'
down_revision: Union[str, Sequence[str], None] = '543ec1728025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('training_dataset_version', sa.String(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_anomaly_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_severity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['ml_model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_anomaly_results_mine_id'), 'ml_anomaly_results', ['mine_id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('model_version_id', sa.String(), nullable=False),
    sa.Column('critical_probability', sa.Float(), nullable=False),
    sa.Column('prediction_class', sa.String(), nullable=False),
    sa.Column('prediction_horizon_days', sa.Integer(), nullable=False),
    sa.Column('top_risk_factors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['ml_model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_mine_id'), 'ml_predictions', ['mine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_predictions_mine_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_ml_anomaly_results_mine_id'), table_name='ml_anomaly_results')
    op.drop_table('ml_anomaly_results')
    op.drop_table('ml_model_versions')
    # ### end Alembic commands ###
