"""Stage 4 migration

Revision ID: 543ec1728025
Revises: d939ec8e428e
Create Date: 2026-08-31 14:34:45.611547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543ec1728025'
down_revision: Union[str, Sequence[str], None] = 'd939ec8e428e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mine_risks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('recurrence_score', sa.Float(), nullable=False),
    sa.Column('corrective_action_score', sa.Float(), nullable=False),
    sa.Column('inspection_score', sa.Float(), nullable=False),
    sa.Column('environment_score', sa.Float(), nullable=False),
    sa.Column('documentation_score', sa.Float(), nullable=False),
    sa.Column('historical_performance_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('calculation_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mine_risks_mine_id'), 'mine_risks', ['mine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mine_risks_mine_id'), table_name='mine_risks')
    op.drop_table('mine_risks')
    # ### end Alembic commands ###
