"""Add FieldEvidence model

Revision ID: 81af4d85113e
Revises: 91a3e490f207
Create Date: 2026-09-03 13:56:25.860372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81af4d85113e'
down_revision: Union[str, Sequence[str], None] = '91a3e490f207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('corrective_action_id', sa.String(), nullable=False),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['corrective_action_id'], ['corrective_actions.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_evidence_corrective_action_id'), 'field_evidence', ['corrective_action_id'], unique=False)
    op.create_index(op.f('ix_field_evidence_mine_id'), 'field_evidence', ['mine_id'], unique=False)
    op.create_index(op.f('ix_field_evidence_submitted_by_user_id'), 'field_evidence', ['submitted_by_user_id'], unique=False)
    with op.batch_alter_table('audit_logs') as batch_op:
        batch_op.alter_column('event_type',
                   existing_type=sa.VARCHAR(length=23),
                   type_=sa.Enum('RECOMMENDATION_CREATED', 'RECOMMENDATION_ACCEPTED', 'RECOMMENDATION_REJECTED', 'ACTION_ASSIGNED', 'ACTION_STARTED', 'ACTION_COMPLETED', 'ACTION_ESCALATED', 'ACTION_VERIFIED', 'ACTION_STATUS_CHANGED', 'FIELD_EVIDENCE_SUBMITTED', 'ACTION_SUBMITTED_FOR_REVIEW', name='auditeventtype'),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs') as batch_op:
        batch_op.alter_column('event_type',
                   existing_type=sa.Enum('RECOMMENDATION_CREATED', 'RECOMMENDATION_ACCEPTED', 'RECOMMENDATION_REJECTED', 'ACTION_ASSIGNED', 'ACTION_STARTED', 'ACTION_COMPLETED', 'ACTION_ESCALATED', 'ACTION_VERIFIED', 'ACTION_STATUS_CHANGED', 'FIELD_EVIDENCE_SUBMITTED', 'ACTION_SUBMITTED_FOR_REVIEW', name='auditeventtype'),
                   type_=sa.VARCHAR(length=23),
                   existing_nullable=False)
    op.drop_index(op.f('ix_field_evidence_submitted_by_user_id'), table_name='field_evidence')
    op.drop_index(op.f('ix_field_evidence_mine_id'), table_name='field_evidence')
    op.drop_index(op.f('ix_field_evidence_corrective_action_id'), table_name='field_evidence')
    op.drop_table('field_evidence')
    # ### end Alembic commands ###
