"""Stage 3 migration

Revision ID: d939ec8e428e
Revises: 391a78117f70
Create Date: 2026-08-31 14:08:17.998315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd939ec8e428e'
down_revision: Union[str, Sequence[str], None] = '391a78117f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('document_number', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'EXPIRING', 'EXPIRED', 'PENDING_REVIEW', name='documentstatus'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_documents_document_number'), 'compliance_documents', ['document_number'], unique=False)
    op.create_index(op.f('ix_compliance_documents_mine_id'), 'compliance_documents', ['mine_id'], unique=False)
    op.create_table('contractors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contractor_code', sa.String(), nullable=False),
    sa.Column('compliance_status', sa.String(), nullable=False),
    sa.Column('training_status', sa.String(), nullable=False),
    sa.Column('certification_status', sa.String(), nullable=False),
    sa.Column('certification_expiry', sa.String(), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_contractor_code'), 'contractors', ['contractor_code'], unique=True)
    op.create_index(op.f('ix_contractors_mine_id'), 'contractors', ['mine_id'], unique=False)
    op.create_table('environment_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'SENSOR', 'IMPORTED', name='environmentsource'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_readings_mine_id'), 'environment_readings', ['mine_id'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('issue_reference_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='actionpriority'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'OVERDUE', 'CLOSED', name='actionstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_assigned_to'), 'corrective_actions', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_corrective_actions_mine_id'), 'corrective_actions', ['mine_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('officer_id', sa.String(), nullable=False),
    sa.Column('inspection_type', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('findings', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'CANCELLED', name='inspectionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_mine_id'), 'inspections', ['mine_id'], unique=False)
    op.create_index(op.f('ix_inspections_officer_id'), 'inspections', ['officer_id'], unique=False)
    op.create_table('safety_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('incident_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_reports_mine_id'), 'safety_reports', ['mine_id'], unique=False)
    op.create_index(op.f('ix_safety_reports_reported_by'), 'safety_reports', ['reported_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_reports_reported_by'), table_name='safety_reports')
    op.drop_index(op.f('ix_safety_reports_mine_id'), table_name='safety_reports')
    op.drop_table('safety_reports')
    op.drop_index(op.f('ix_inspections_officer_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_mine_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_corrective_actions_mine_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_assigned_to'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_environment_readings_mine_id'), table_name='environment_readings')
    op.drop_table('environment_readings')
    op.drop_index(op.f('ix_contractors_mine_id'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_contractor_code'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_compliance_documents_mine_id'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_document_number'), table_name='compliance_documents')
    op.drop_table('compliance_documents')
    # ### end Alembic commands ###
