"""add incident report

Revision ID: eaeb8bd4fa42
Revises: d11c8cb37870
Create Date: 2026-09-04 19:00:58.356891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaeb8bd4fa42'
down_revision: Union[str, Sequence[str], None] = 'd11c8cb37870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('SAFETY', 'ENVIRONMENT', 'COMPLIANCE', 'EQUIPMENT', 'OTHER', name='incidentcategory'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reporter_name', sa.String(), nullable=True),
    sa.Column('reporter_contact', sa.String(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('linked_action_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['linked_action_id'], ['corrective_actions.id'], ),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_mine_id'), 'incident_reports', ['mine_id'], unique=False)
    op.create_table('evidence_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=False),
    sa.Column('analysis_summary', sa.String(), nullable=True),
    sa.Column('detected_indicators', sa.JSON(), nullable=True),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['field_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_analysis_evidence_id'), 'evidence_analysis', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_analysis_evidence_id'), table_name='evidence_analysis')
    op.drop_table('evidence_analysis')
    op.drop_index(op.f('ix_incident_reports_mine_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    # ### end Alembic commands ###
