import enum

class UserRole(str, enum.Enum):
    HEAD_ADMIN = "HEAD_ADMIN"
    REGIONAL_MANAGER = "REGIONAL_MANAGER"
    AREA_MANAGER = "AREA_MANAGER"
    MINE_MANAGER = "MINE_MANAGER"
    SUPERVISOR = "SUPERVISOR"
    SAFETY_OFFICER = "SAFETY_OFFICER"
    ENVIRONMENTAL_OFFICER = "ENVIRONMENTAL_OFFICER"
    CONTRACTOR_OFFICER = "CONTRACTOR_OFFICER"
    FIELD_OFFICER = "FIELD_OFFICER"
    AUDITOR_REGULATOR = "AUDITOR_REGULATOR"

class MineZoneType(str, enum.Enum):
    PIT = "PIT"
    HAUL_ROAD = "HAUL_ROAD"
    PROCESSING = "PROCESSING"
    STOCKYARD = "STOCKYARD"
    WORKER_AREA = "WORKER_AREA"
    ENVIRONMENTAL = "ENVIRONMENTAL"

class RiskLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class DepartmentType(str, enum.Enum):
    SAFETY = "SAFETY"
    ENVIRONMENT = "ENVIRONMENT"
    CONTRACTOR = "CONTRACTOR"
    INSPECTION = "INSPECTION"
    COMPLIANCE = "COMPLIANCE"
    CORRECTIVE_ACTION = "CORRECTIVE_ACTION"

class MineStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"

class IncidentCategory(str, enum.Enum):
    SAFETY = "SAFETY"
    ENVIRONMENT = "ENVIRONMENT"
    COMPLIANCE = "COMPLIANCE"
    EQUIPMENT = "EQUIPMENT"
    OTHER = "OTHER"

class IncidentSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class IncidentStatus(str, enum.Enum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"

class EnvironmentSource(str, enum.Enum):
    MANUAL = "MANUAL"
    SENSOR = "SENSOR"
    IMPORTED = "IMPORTED"

class InspectionStatus(str, enum.Enum):
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"
    CANCELLED = "CANCELLED"

class DocumentStatus(str, enum.Enum):
    VALID = "VALID"
    EXPIRING = "EXPIRING"
    EXPIRED = "EXPIRED"
    PENDING_REVIEW = "PENDING_REVIEW"

class ActionPriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ActionStatus(str, enum.Enum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    IN_REVIEW = "IN_REVIEW"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"
    OVERDUE = "OVERDUE"
    CLOSED = "CLOSED"

class RecommendationSource(str, enum.Enum):
    BASELINE_RISK = "BASELINE_RISK"
    XGBOOST = "XGBOOST"
    ISOLATION_FOREST = "ISOLATION_FOREST"
    SHAP = "SHAP"
    SAFETY = "SAFETY"
    ENVIRONMENT = "ENVIRONMENT"
    COMPLIANCE = "COMPLIANCE"
    INSPECTION = "INSPECTION"
    CONTRACTOR = "CONTRACTOR"
    MULTI_FACTOR = "MULTI_FACTOR"

class RecommendationStatus(str, enum.Enum):
    PENDING = "PENDING"
    RECOMMENDED = "RECOMMENDED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    CONVERTED_TO_ACTION = "CONVERTED_TO_ACTION"
    COMPLETED = "COMPLETED"
    EXPIRED = "EXPIRED"

class TaskStatus(str, enum.Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    DISMISSED = "DISMISSED"

class AuditEventType(str, enum.Enum):
    RECOMMENDATION_CREATED = "RECOMMENDATION_CREATED"
    RECOMMENDATION_ACCEPTED = "RECOMMENDATION_ACCEPTED"
    RECOMMENDATION_REJECTED = "RECOMMENDATION_REJECTED"
    ACTION_ASSIGNED = "ACTION_ASSIGNED"
    ACTION_STARTED = "ACTION_STARTED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    ACTION_ESCALATED = "ACTION_ESCALATED"
    ACTION_VERIFIED = "ACTION_VERIFIED"
    ACTION_STATUS_CHANGED = "ACTION_STATUS_CHANGED"
    FIELD_EVIDENCE_SUBMITTED = "FIELD_EVIDENCE_SUBMITTED"
    ACTION_SUBMITTED_FOR_REVIEW = "ACTION_SUBMITTED_FOR_REVIEW"
    DAILY_TASKS_GENERATED = "DAILY_TASKS_GENERATED"
    FIELD_EVIDENCE_ANALYZED = "FIELD_EVIDENCE_ANALYZED"
    INCIDENT_SUBMITTED = "INCIDENT_SUBMITTED"
    INCIDENT_REVIEWED = "INCIDENT_REVIEWED"
    INCIDENT_ESCALATED = "INCIDENT_ESCALATED"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    RISK_RECALCULATED = "RISK_RECALCULATED"
    GOVERNANCE_POINTS_AWARDED = "GOVERNANCE_POINTS_AWARDED"
    SENSOR_ANOMALY_TRIGGERED = "SENSOR_ANOMALY_TRIGGERED"
    TELEMETRY_INGESTED = "TELEMETRY_INGESTED"
    INSPECTION_COMPLETED = "INSPECTION_COMPLETED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"

class AnalysisEngine(str, enum.Enum):
    DEMO_ANALYZER = "DEMO_ANALYZER"
    OCR_ENGINE = "OCR_ENGINE"
    VISION_ENGINE = "VISION_ENGINE"

class AnalysisStatus(str, enum.Enum):
    PENDING = "PENDING"
    ANALYZED = "ANALYZED"
    FAILED = "FAILED"

