"""Add IoT tables

Revision ID: 6d55db33dba7
Revises: eaeb8bd4fa42
Create Date: 2026-09-05 14:26:21.062005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d55db33dba7'
down_revision: Union[str, Sequence[str], None] = 'eaeb8bd4fa42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_sensors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mine_id', sa.String(length=36), nullable=False),
    sa.Column('sensor_name', sa.String(), nullable=False),
    sa.Column('sensor_type', sa.Enum('PM10', 'PM25', 'TEMPERATURE', 'METHANE', 'CO', 'DUST', 'VIBRATION', 'NOISE', 'HUMIDITY', name='sensortype'), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'MAINTENANCE', 'DEGRADED', name='sensorstatus'), nullable=True),
    sa.Column('threshold_warning', sa.Float(), nullable=False),
    sa.Column('threshold_critical', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sensor_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['iot_sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry')
    op.drop_table('iot_sensors')
    # ### end Alembic commands ###
