"""Add DailyTask

Revision ID: d11c8cb37870
Revises: 81af4d85113e
Create Date: 2026-09-04 00:02:10.213799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11c8cb37870'
down_revision: Union[str, Sequence[str], None] = '81af4d85113e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('mine_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('HEAD_ADMIN', 'REGIONAL_MANAGER', 'AREA_MANAGER', 'MINE_MANAGER', 'SAFETY_OFFICER', 'ENVIRONMENTAL_OFFICER', 'CONTRACTOR_OFFICER', 'FIELD_OFFICER', 'AUDITOR_REGULATOR', name='userrole'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'DISMISSED', name='taskstatus'), nullable=False),
    sa.Column('generation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_tasks_generation_date'), 'daily_tasks', ['generation_date'], unique=False)
    op.create_index(op.f('ix_daily_tasks_mine_id'), 'daily_tasks', ['mine_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_role'), 'daily_tasks', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_tasks_role'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_mine_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_generation_date'), table_name='daily_tasks')
    op.drop_table('daily_tasks')
    # ### end Alembic commands ###
